version = 2

test_patterns = [
    "tests/**",
    "test_*.py"
]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
      "bot.dockerfile",
#      "api.dockerfile"
  ]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "pyproject.toml",
    "poetry.lock"
]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"
enabled = true