services:

    bot:
        container_name: bot
        restart: always
        environment:
            - PIP_DEFAULT_TIMEOUT=100
            - PIP_DISABLE_PIP_VERSION_CHECK=1
            - PIP_NO_CACHE_DIR=1
            - PYTHONUNBUFFERED=1
        build:
            dockerfile: bot.dockerfile
            context: .
            target: prod
    #    depends_on:
    #      - db

    api:
        container_name: api
        restart: always
        ports:
            - 8084:${PORT:-8084}
        build:
            dockerfile: api.dockerfile
            context: .
            target: prod
    #    depends_on:
    #        - db

#    db:
#        image: postgres
#        restart: always
#        ports:
#            - 5432:5432
#        volumes:
#            - db-data:/var/lib/postgresql/data


#volumes:
#    db-data:

#volumes:
#    -   type: bind
#        source: .
#        target: /app
#        volume:
#            nocopy: true