services:

  bot:
    container_name: bot
    restart: always
    environment:
      ENV PIP_DEFAULT_TIMEOUT: 100
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_NO_CACHE_DIR: 1
      PYTHONUNBUFFERED: 1
      #POETRY_VERSION: 1.0.5
    build:
      dockerfile: Dockerfile.bot
      context: .
    depends_on:
      - pgdb

#  api:
#    container_name: api
#    restart: always
#    ports:
#      - 8081:80
#    build:
#      dockerfile: Dockerfile.api
#      context: .

  pgdb:
    container_name: pgdb
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres1
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres3
#    env_file:
#      - .db.env
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#volumes:
#  db-data: