[tool.poetry]
name = "letovoAnalytics"
version = "1.0.0"
description = "Letovo Analytics bot helps letovians access s.letovo.ru resources via Telegram"
authors = ["arsikurin <arseny.kurin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10.0"
requests = "^2.26.0"
requests-futures = "^1.0.0"
firebase-admin = "^5.0.3"
Telethon = "^1.23.0"
colourlib = "^0.5.3"
PyYAML = "^5.4.1"
cryptg = "^0.2.post4"
psycopg2-binary = "^2.9.1"
Jinja2 = "^3.0.2"
fastapi = "^0.70.0"
aiofiles = "^0.7.0"
uvicorn = "^0.15.0"
python-multipart = "^0.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
